all:
	javac ./jchandr2_java_part2/*.java
	javac assignmentP3.java

clean:
	rm -r *.class
	rm -r ./jchandr2_java_part2/*.class
	rm -r ./jchandr2_java_part2/*.csv
	rm -r ./jchandr2_java_part2/*.txt
	rm -r *.txt